---
sidebar: sidebar 
permalink: use-acp/acp-snap-restore.html 
keywords: snapshot restore, snapshot, astra control provisioner, TridentActionSnapshotRestore, 
summary: 'Astra Control Provisioning permite restaurar volúmenes rápidamente sin movimiento a partir de una copia Snapshot mediante el `TridentActionSnapshotRestore` (TASR) CR. Esta CR funciona como una acción imprescindible de Kubernetes y no persiste una vez que finaliza la operación.' 
---
= Recuperar datos de volumen mediante una copia Snapshot
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Provisioning permite restaurar volúmenes rápidamente sin movimiento a partir de una copia Snapshot mediante el `TridentActionSnapshotRestore` (TASR) CR. Esta CR funciona como una acción imprescindible de Kubernetes y no persiste una vez que finaliza la operación.

Astra Control Provisioner admite la restauración de copias Snapshot en el `ontap-san`, `ontap-san-economy`, `ontap-nas`, `ontap-nas-flexgroup`, `azure-netapp-files`, `gcp-cvs`, y. `solidfire-san` de windows

.Antes de empezar
Debe tener una snapshot de volumen disponible y la RVP vinculada.

* Compruebe que el estado de la RVP es de enlace.
+
[listing]
----
kubectl get pvc
----
* Compruebe que la copia de Snapshot de volumen esté lista para utilizarse.
+
[listing]
----
kubectl get vs
----


.Pasos
. Cree el CR de TASR. En este ejemplo se crea una CR para la RVP `pvc1` y copia de snapshot de volumen `pvc1-snapshot`.
+
[listing]
----
cat tasr-pvc1-snapshot.yaml

apiVersion: v1
kind: TridentActionSnapshotRestore
metadata:
  name: this-doesnt-matter
  namespace: trident
spec:
  pvcName: pvc1
  volumeSnapshotName: pvc1-snapshot
----
. Aplique el CR para restaurar a partir de la instantánea. En este ejemplo se restaura a partir de una copia Snapshot `pvc1`.
+
[listing]
----
kubectl create -f tasr-pvc1-snapshot.yaml

tridentactionsnapshotrestore.trident.netapp.io/this-doesnt-matter created
----


.Resultados
El aprovisionador de Astra Control restaura los datos a partir de la snapshot. Es posible verificar el estado de restauración de la Snapshot.

[listing]
----
kubectl get tasr -o yaml

apiVersion: v1
items:
- apiVersion: trident.netapp.io/v1
  kind: TridentActionSnapshotRestore
  metadata:
    creationTimestamp: "2023-04-14T00:20:33Z"
    generation: 3
    name: this-doesnt-matter
    namespace: trident
    resourceVersion: "3453847"
    uid: <uid>
  spec:
    pvcName: pvc1
    volumeSnapshotName: pvc1-snapshot
  status:
    startTime: "2023-04-14T00:20:34Z"
    completionTime: "2023-04-14T00:20:37Z"
    state: Succeeded
kind: List
metadata:
  resourceVersion: ""
----
[NOTE]
====
* En la mayoría de los casos, el aprovisionador de Astra Control no volverá a intentar automáticamente la operación en caso de fallo. Deberá realizar la operación de nuevo.
* Es posible que el administrador deba conceder permiso al usuario de Kubernetes sin acceso de administrador para crear una CR TASR en su espacio de nombres de la aplicación.


====