---
sidebar: sidebar 
permalink: use/log-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account 
summary: Puede acceder al servicio Astra Control mediante una interfaz de usuario basada en SaaS en astra.netapp.io. 
---
= Inicie sesión en el servicio Astra Control
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se puede acceder al servicio Astra Control mediante una interfaz de usuario basada en SaaS https://astra.netapp.io[].


TIP: Puede utilizar el inicio de sesión único para iniciar sesión con credenciales del directorio corporativo (identidad federada). Para obtener más información, visite la https://cloud.netapp.com/help-center["Centro de ayuda de Cloud Central"^] Y, a continuación, seleccione *Opciones de inicio de sesión de Cloud Central*.

.Lo que necesitará
* link:../get-started/register.html["Un ID de usuario de Cloud Central"].
* link:../get-started/register.html["Una nueva cuenta de Astra Control"] o. link:manage-users.html["una invitación a una cuenta existente"].
* Un navegador web compatible.
+
Astra Control Service es compatible con las versiones recientes de Firefox, Safari y Chrome con una resolución mínima de 1280 x 720.



.Pasos
. Abra un explorador web y vaya a. https://astra.netapp.io[].
. Inicie sesión con sus credenciales de Cloud Central de NetApp.

