---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: Gestione los bloques que Astra utiliza para backups y clones mediante la adición de bloques adicionales y el cambio del bloque predeterminado para los clústeres de su proveedor de cloud. 
---
= Gestionar bloques
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Puede gestionar los bloques que Astra utiliza para backups y clones. Puede añadir bloques adicionales, quitar bloques existentes y cambiar el bloque predeterminado para los clústeres de Kubernetes en una instancia de cloud.

Solo los propietarios y administradores pueden gestionar los bloques.



== Cómo utiliza el control Astra cucharones

Cuando empiece a gestionar su primer clúster Kubernetes para una instancia de cloud, Astra Control Service crea el bloque inicial para este fin link:manage-cloud-instances.html["instancia de cloud"^].

Puede designar manualmente un bloque como el bloque predeterminado para una instancia de cloud. Si lo hace, Astra Control Service utiliza este bloque de forma predeterminada para las copias de seguridad y clones que cree en cualquier clúster gestionado de esa instancia cloud (puede seleccionar un bloque diferente para las copias de seguridad). Si clona una aplicación en vivo desde cualquiera de los clústeres gestionados de una instancia de cloud a otro clúster, Astra Control Service utiliza el bloque predeterminado para la instancia de cloud de origen para realizar la operación de clonado.

Puede establecer el mismo bloque que el bloque predeterminado para varias instancias de cloud.

Puede seleccionar desde cualquier grupo cuando crea una política de protección o inicia un backup ad hoc.


TIP: El servicio Astra Control Service comprueba si se puede acceder a un bloque de destino antes de iniciar una copia de seguridad o un clon.



== Ver los bloques existentes

Consulte la lista de bloques disponibles para Astra Control Service para determinar su estado e identificar el bloque predeterminado (si se ha definido) para su instancia de cloud.

Un bloque puede tener cualquiera de los siguientes estados:

Pendiente:: Después de añadir un cucharón, se inicia en el estado pendiente mientras Astra Control lo detecta.
Disponible:: El cucharón está disponible para su uso por Astra Control.
Quitada:: La cuchara no está operativa por el momento. Pase el ratón sobre el icono de estado para identificar el problema.
+
--
Si un bloque se encuentra en el estado quitado, puede establecerlo como el bloque predeterminado y asignarlo a un programa de protección. Pero si el bloque no está en estado disponible cuando se inicia una operación de protección de datos, esta operación falla.

--


.Paso
. Vaya a *Cuchos*.
+
Se muestra la lista de cucharones disponibles para el servicio de control de Astra.





== Añadir un bloque más

Puede añadir cubos adicionales en cualquier momento. Esto le permite elegir entre bloques al crear una política de protección o iniciar un backup ad hoc, y le permite cambiar el bloque predeterminado que utiliza una instancia de cloud.

Puede añadir los siguientes tipos de cubos:

* Amazon Web Services
* Genérico S3
* Google Cloud Platform
* Microsoft Azure
* ONTAP S3 de NetApp
* StorageGRID S3 de NetApp


.Antes de empezar
* El nombre de un bloque existente.
* Las credenciales del bloque que proporcionan a Astra Control Service los permisos que necesita para gestionar el bloque.


ifdef::azure[]

* Si su bloque está en Microsoft Azure:
+
** El bloque debe pertenecer al grupo de recursos denominado _astra-backup-rg_.
** Si la configuración del rendimiento de la instancia de la cuenta de almacenamiento de Azure se establece en "Premium", la opción "Tipo de cuenta Premium" debe configurarse en "Block Blobs".




endif::azure[]

.Pasos
. Vaya a *Cuchos*.
. Seleccione *Agregar* y siga las indicaciones para añadir el cucharón.
+
** *Tipo*: Elija su proveedor de nube.
** *Nombre del cucharón existente*: Introduzca el nombre del cucharón.
** *Descripción*: Si lo desea, introduzca una descripción del cucharón.




ifdef::azure[]

* *Cuenta de almacenamiento* (sólo Azure): Introduzca el nombre de su cuenta de almacenamiento de Azure. Este bloque debe pertenecer al grupo de recursos denominado _astra-backup-rg_.


endif::azure[]

ifdef::aws[]

* *Nombre de servidor S3 o dirección IP* (sólo tipos de bloques AWS y S3): Introduzca el nombre de dominio completo del extremo S3 que corresponda a su región, sin `https://`. Consulte https://["La documentación de Amazon"^] si quiere más información.


endif::aws[]

* *Seleccionar credenciales*: Introduzca las credenciales que proporcionan a Astra Control Service los permisos que necesita para administrar el bloque. La información que debe proporcionar varía en función del tipo de segmento.
+
.. Seleccione *Agregar* para añadir el cucharón.




.Resultado
Astra Control Service añade el cucharón. Ahora puede elegir este bloque cuando cree una política de protección o ejecute un backup ad hoc. También puede establecer este bloque como el bloque predeterminado para una instancia de cloud.



== Cambiar el bloque predeterminado

Puede cambiar el bloque predeterminado para una instancia de cloud. Astra Control Service utilizará este bloque de forma predeterminada para las copias de seguridad y clones. Cada instancia de cloud tiene su propio bloque predeterminado.


NOTE: Astra Control no asigna automáticamente un bloque predeterminado para ninguna instancia de cloud. Debe establecer manualmente un bloque predeterminado para una instancia de cloud antes de ejecutar operaciones de clonado de aplicaciones entre dos clústeres.

.Pasos
. Vaya a *instancias de cloud*.
. Seleccione el menú de configuración de la columna *acciones* para la instancia de nube que desea editar.
. Seleccione *Editar*.
. En la lista de bloques, seleccione el bloque que desea convertir en el bloque predeterminado para esta instancia de cloud.
. Seleccione *Actualizar*.




== Retirar un cucharón

Puede eliminar un cubo que ya no esté en uso o que no esté sano. Se recomienda hacer esto para mantener la configuración del almacén de objetos sencilla y actualizada.

No se puede eliminar un bloque predeterminado. Si desea eliminar ese bloque, seleccione primero otro bloque como predeterminado.

.Antes de empezar
* Antes de empezar, debe comprobar que no hay copias de seguridad en ejecución o completadas para este bloque.
* Debe comprobar que dicho bloque no se esté utilizando para ninguna copia de seguridad programada.


Si lo hay, no podrá continuar.

.Pasos
. Vaya a *Cuchos*.
. En el menú *acciones*, seleccione *Quitar*.
+

NOTE: Astra Control garantiza en primer lugar que no existan normativas de programación utilizando el bloque para copias de seguridad y que no haya copias de seguridad activas en el bloque que va a eliminar.

. Escriba "eliminar" para confirmar la acción.
. Seleccione *Sí, retire la cuchara*.




== Obtenga más información

* https://["Utilice la API Astra Control"^]

