---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: Añada y elimine credenciales de proveedor de cloud de su cuenta en cualquier momento. Astra Control utiliza estas credenciales para aprovisionar recursos en su nombre. 
---
= Añada y elimine credenciales
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Añada y elimine credenciales de proveedor de cloud de su cuenta en cualquier momento. Astra Control utiliza estas credenciales para descubrir un clúster de Kubernetes, las aplicaciones en el clúster y aprovisionar recursos en su nombre.

Tenga en cuenta que todos los usuarios de Astra Control comparten los mismos conjuntos de credenciales.



== Añada credenciales

La forma más común de agregar credenciales a Astra Control es cuando se gestionan los clústeres, pero también se pueden añadir credenciales desde la página cuenta. De ese modo, las credenciales estarán disponibles para elegir cuando gestione clústeres de Kubernetes adicionales.

.Lo que necesitará
ifdef::aws[]

* Para Amazon Web Services, debe tener el resultado JSON de las credenciales de la cuenta IAM que se utiliza para crear el clúster. link:../get-started/set-up-amazon-web-services.html["Aprenda a configurar un usuario de IAM"].


endif::aws[]

ifdef::gcp[]

* Para GKE, debe tener el archivo de clave de cuenta de servicio para una cuenta de servicio que tenga los permisos necesarios. link:../get-started/set-up-google-cloud.html["Aprenda a configurar una cuenta de servicio"].


endif::gcp[]

ifdef::azure[]

* Para AKS, debe tener el archivo JSON que contenga el resultado de la CLI de Azure cuando creó el principal de servicio. link:../get-started/set-up-microsoft-azure-with-anf.html["Aprenda a configurar un director de servicios"].
+
También necesitará su ID de suscripción de Azure si no lo ha añadido al archivo JSON.



endif::azure[]

.Pasos
. Seleccione *cuenta > credenciales*.
. Seleccione *Agregar credenciales*.


ifdef::azure[]

. Seleccione *Microsoft Azure*.


endif::azure[]

ifdef::gcp[]

. Seleccione *Google Cloud Platform*.


endif::gcp[]

ifdef::aws[]

. Seleccione *Amazon Web Services*.


endif::aws[]

. Introduzca un nombre para las credenciales que las distinga de otras credenciales en Astra Control.
. Proporcione las credenciales necesarias.


ifdef::azure[]

. *Microsoft Azure*: Proporcione a Astra Control detalles sobre el principal de servicio de Azure cargando un archivo JSON o pegando el contenido de ese archivo JSON desde el portapapeles.
+
El archivo JSON debe contener el resultado de la CLI de Azure al crear el principal del servicio. También puede incluir su ID de suscripción para que se agregue automáticamente a Astra Control. De lo contrario, deberá introducir manualmente el ID después de proporcionar JSON.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Proporcione el archivo clave de la cuenta de servicio de Google Cloud mediante la carga del archivo o pegando el contenido del portapapeles.


endif::gcp[]

ifdef::aws[]

. *Amazon Web Services*: Proporcione las credenciales de usuario de IAM de Amazon Web Services cargando el archivo o pegando el contenido del portapapeles.


endif::aws[]

. Seleccione *Agregar credenciales*.


.Resultado
Las credenciales ahora están disponibles para seleccionar cuando agregue un clúster a Astra Control.



== Quite las credenciales

Eliminar credenciales de una cuenta en cualquier momento. Solo debe quitar credenciales después de link:unmanage.html["desgestione todos los clústeres"], a menos que esté rotando credenciales (consulte <<Rotar credenciales>>).


NOTE: El primer conjunto de credenciales que agregue a Astra Control siempre está en uso porque Astra Control utiliza las credenciales para autenticarse en el bloque de copia de seguridad. Lo mejor es no eliminar estas credenciales.

.Pasos
. Seleccione *cuenta > credenciales*.
. Seleccione la lista desplegable de la columna *Estado* para las credenciales que desea quitar.
. Seleccione *Quitar*.
. Escriba el nombre de las credenciales que desea confirmar la eliminación y, a continuación, seleccione *Sí, Eliminar credenciales*.


.Resultado
Astra Control elimina las credenciales de la cuenta.



== Rotar credenciales

Puede rotar credenciales en su cuenta. Si gira las credenciales, gírelos durante una ventana de mantenimiento cuando no haya copias de seguridad en curso (programadas o bajo demanda).

.Pasos
. Elimine las credenciales existentes siguiendo los pasos de <<Quite las credenciales>>.
. Añada las nuevas credenciales siguiendo los pasos del <<Añada credenciales>>.
. Actualice todos los bloques para usar las credenciales nuevas:
+
.. En la navegación de la izquierda, seleccione *Cuchos*.
.. Seleccione la lista desplegable en la columna *acciones* para el segmento que desea editar.
.. Seleccione *Editar*.
.. En la sección *Seleccionar credenciales*, elija las nuevas credenciales que agregó a Astra Control.
.. Seleccione *Actualizar*.
.. Repita los pasos *b* a *e* para los cucharones restantes del sistema.




.Resultado
Astra Control empieza a utilizar las nuevas credenciales del proveedor de cloud.
