---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: Gestione los bloques que Astra utiliza para backups y clones mediante la adición de bloques adicionales y el cambio del bloque predeterminado para los clústeres de su proveedor de cloud. 
---
= Gestionar bloques
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Puede gestionar los bloques que Astra utiliza para backups y clones. Puede añadir bloques adicionales, quitar bloques existentes y cambiar el bloque predeterminado para los clústeres de Kubernetes en una instancia de cloud.

Solo los propietarios y administradores pueden gestionar los bloques.



== Cómo utiliza el control Astra cucharones

Cuando empiece a gestionar su primer clúster Kubernetes para una instancia de cloud, Astra Control Service crea el bloque inicial para este fin link:manage-cloud-instances.html["instancia de cloud"^].

Puede designar manualmente un bloque como el bloque predeterminado para una instancia de cloud. Si lo hace, Astra Control Service utiliza este bloque de forma predeterminada para las copias de seguridad y clones que cree en cualquier clúster gestionado de esa instancia cloud (puede seleccionar un bloque diferente para las copias de seguridad). Si clona una aplicación en vivo desde cualquiera de los clústeres gestionados de una instancia de cloud a otro clúster, Astra Control Service utiliza el bloque predeterminado para la instancia de cloud de origen para realizar la operación de clonado.

Puede establecer el mismo bloque que el bloque predeterminado para varias instancias de cloud.

Puede seleccionar desde cualquier grupo cuando crea una política de protección o inicia un backup ad hoc.


TIP: El servicio Astra Control Service comprueba si se puede acceder a un bloque de destino antes de iniciar una copia de seguridad o un clon.



== Ver los bloques existentes

Consulte la lista de bloques disponibles para Astra Control Service para determinar su estado e identificar el bloque predeterminado (si se ha definido) para su instancia de cloud.

Un bloque puede tener cualquiera de los siguientes estados:

Pendiente:: Después de añadir un cucharón, se inicia en el estado pendiente mientras Astra Control lo detecta.
Disponible:: El cucharón está disponible para su uso por Astra Control.
Quitada:: La cuchara no está operativa por el momento. Pase el ratón sobre el icono de estado para identificar el problema.
+
--
Si un bloque se encuentra en el estado quitado, puede establecerlo como el bloque predeterminado y asignarlo a un programa de protección. Pero si el bloque no está en estado disponible cuando se inicia una operación de protección de datos, esta operación falla.

--


.Paso
. Vaya a *Cuchos*.
+
Se muestra la lista de cucharones disponibles para el servicio de control de Astra.





== Añadir un bloque más

Puede añadir cubos adicionales en cualquier momento. Esto le permite elegir entre bloques al crear una política de protección o iniciar un backup ad hoc, y le permite cambiar el bloque predeterminado que utiliza una instancia de cloud.

Puede añadir los siguientes tipos de cubos:

* Amazon Web Services
* Genérico S3
* Google Cloud Platform
* Microsoft Azure
* ONTAP S3 de NetApp
* StorageGRID S3 de NetApp


.Antes de empezar
* Asegúrese de conocer el nombre de un depósito existente.
* Asegúrate de tener credenciales para el bloque que proporcionan a Astra Control los permisos que necesita para gestionar el bloque.


ifdef::azure[]

* Si su bloque está en Microsoft Azure:
+
** El bloque debe pertenecer al grupo de recursos denominado _astra-backup-rg_.
** Si la configuración del rendimiento de la instancia de la cuenta de almacenamiento de Azure se establece en "Premium", la opción "Tipo de cuenta Premium" debe configurarse en "Block Blobs".




endif::azure[]

.Pasos
. Vaya a *Cuchos*.
. Seleccione *Agregar* y siga las indicaciones para añadir el cucharón.
+
** *Tipo*: Elija su proveedor de nube.
** *Nombre del cucharón existente*: Introduzca el nombre del cucharón.
** *Descripción*: Si lo desea, introduzca una descripción del cucharón.




ifdef::azure[]

* *Cuenta de almacenamiento* (sólo Azure): Introduzca el nombre de su cuenta de almacenamiento de Azure. Este bloque debe pertenecer al grupo de recursos denominado _astra-backup-rg_.


endif::azure[]

ifdef::aws[]

* *Nombre de servidor S3 o dirección IP* (sólo tipos de bloques AWS y S3): Introduzca el nombre de dominio completo del extremo S3 que corresponda a su región, sin `https://`. Consulte https://docs.aws.amazon.com/general/latest/gr/s3.html["La documentación de Amazon"^] si quiere más información.


endif::aws[]

* *Seleccionar credenciales*: Introduzca las credenciales que proporcionan a Astra Control Service los permisos que necesita para administrar el bloque. La información que debe proporcionar varía en función del tipo de segmento.
+
.. Seleccione *Agregar* para añadir el cucharón.




.Resultado
Astra Control Service añade el cucharón. Ahora puede elegir este bloque cuando cree una política de protección o ejecute un backup ad hoc. También puede establecer este bloque como el bloque predeterminado para una instancia de cloud.



== Cambiar el bloque predeterminado

Puede cambiar el bloque predeterminado para una instancia de cloud. Astra Control Service utilizará este bloque de forma predeterminada para las copias de seguridad y clones. Cada instancia de cloud tiene su propio bloque predeterminado.


NOTE: Astra Control no asigna automáticamente un bloque predeterminado para ninguna instancia de cloud. Debe establecer manualmente un bloque predeterminado para una instancia de cloud antes de ejecutar operaciones de clonado de aplicaciones entre dos clústeres.

.Pasos
. Vaya a *instancias de cloud*.
. Seleccione el menú de configuración de la columna *acciones* para la instancia de nube que desea editar.
. Seleccione *Editar*.
. En la lista de bloques, seleccione el bloque que desea convertir en el bloque predeterminado para esta instancia de cloud.
. Seleccione *Actualizar*.




== Retirar un cucharón

Puede eliminar un cubo que ya no esté en uso o que no esté sano. Se recomienda hacer esto para mantener la configuración del almacén de objetos sencilla y actualizada.

[NOTE]
====
* No se puede eliminar un bloque predeterminado. Si desea eliminar ese bloque, seleccione primero otro bloque como predeterminado.
* No puede quitar un depósito de escritura única y lectura múltiple (WORM) antes de que haya caducado el período de retención del proveedor de cloud del depósito. Los depósitos WORM están marcados con «bloqueados» junto al nombre del bloque.


====
.Antes de empezar
* Antes de empezar, debe comprobar que no hay copias de seguridad en ejecución o completadas para este bloque.
* Debe comprobar que dicho bloque no se esté utilizando para ninguna copia de seguridad programada.


Si lo hay, no podrá continuar.

.Pasos
. Vaya a *Cuchos*.
. En el menú *acciones*, seleccione *Quitar*.
+

NOTE: Astra Control garantiza en primer lugar que no existan normativas de programación utilizando el bloque para copias de seguridad y que no haya copias de seguridad activas en el bloque que va a eliminar.

. Escriba "eliminar" para confirmar la acción.
. Seleccione *Sí, retire la cuchara*.




== [Vista PREVIA TÉCNICA] Gestione un bloque con un recurso personalizado

Puede añadir un bloque con un recurso personalizado de Astra Control (CR) en el clúster de aplicaciones. Añadir proveedores de bloques de almacenamiento de objetos es esencial si desea realizar backups de sus aplicaciones y del almacenamiento persistente o si desea clonar aplicaciones entre clústeres. Astra Control almacena estas copias de seguridad o clones en los bloques de almacenamiento de objetos que defina. Si utiliza el método de recursos personalizado, la funcionalidad de snapshots de aplicaciones requiere un bloque.

No necesita un bloque de Astra Control si clona la configuración de sus aplicaciones y el almacenamiento persistente en el mismo clúster.

El recurso personalizado de bloque para Astra Control se conoce como AppVault. Este CR contiene las configuraciones necesarias para que un cucharón se utilice en operaciones de protección.

.Antes de empezar
* Asegúrese de tener un bloque al que se puede acceder desde los clústeres que gestiona Astra Control Center.
* Asegúrese de tener credenciales para el bloque.
* Asegúrese de que el cucharón es uno de los siguientes tipos:
+
** ONTAP S3 de NetApp
** StorageGRID S3 de NetApp
** Microsoft Azure
** Genérico S3





NOTE: Amazon Web Services (AWS) y Google Cloud Platform (GCP) utilizan el tipo de bloque Generic S3.


NOTE: Aunque Astra Control Center es compatible con Amazon S3 como proveedor de bloques Generic S3, es posible que Astra Control Center no admita todos los proveedores de almacenes de objetos que afirman que Amazon es compatible con S3.

.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre (por ejemplo, `astra-appvault.yaml`).
. Configure los siguientes atributos:
+
** *metadata.name*: _(required)_ El nombre del recurso personalizado de AppVault.
** *Spec.prefix*: _(Opcional)_ Una ruta que tiene el prefijo de los nombres de todas las entidades almacenadas en AppVault.
** *spec.providerConfig*: _(required)_ Almacena la configuración necesaria para acceder a AppVault utilizando el proveedor especificado.
** *spec.providerCredentials*: _(required)_ Almacena referencias a cualquier credencial necesaria para acceder a AppVault utilizando el proveedor especificado.
+
*** *spec.providerCredentials.valueFromSecret*: _(Opcional)_ indica que el valor de la credencial debe provenir de un secreto.
+
**** *KEY*: _(requerido si se usa valueFromSecret)_ La clave válida del secreto para seleccionar.
**** *Name*: _(requerido si se usa valueFromSecret)_ Nombre del secreto que contiene el valor de este campo. Debe estar en el mismo espacio de nombres.




** *spec.providerType*: _(required)_ Determina qué proporciona la copia de seguridad; por ejemplo, NetApp ONTAP S3 o Microsoft Azure.
+
Ejemplo YAML:

+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: astra-appvault
spec:
  providerType: generic-s3
  providerConfig:
    path: testpath
    endpoint: 192.168.1.100:80
    bucketName: bucket1
    secure: "false"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: s3-creds
        key: accessKeyID
    secretAccessKey:
      valueFromSecret:
        name: s3-creds
        key: secretAccessKey
----


. Después de rellenar el `astra-appvault.yaml` Con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f astra-appvault.yaml -n astra-connector
----
+

NOTE: Cuando se agrega un bloque, Astra Control Marca un bloque con el indicador de segmento predeterminado. El primer bloque que crea se convierte en el bloque predeterminado. A medida que se añaden bloques, más adelante se puede decidir a. link:../use/manage-buckets.html#set-the-default-bucket["establecer otro bloque predeterminado"^].





== Obtenga más información

* https://docs.netapp.com/us-en/astra-automation/index.html["Utilice la API Astra Control"^]

