---
sidebar: sidebar 
permalink: use/monitor-running-tasks.html 
keywords: activity, log, activities, running, tasks, monitor, status, state 
summary: Puede ver detalles sobre las tareas en ejecución en Astra Control. Por ejemplo, cuando se realiza una copia de Snapshot, un backup o un clon. 
---
= Supervisar tareas en ejecución
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Puede ver detalles sobre las tareas en ejecución y las tareas que se han completado, han fallado o han sido canceladas en las últimas 24 horas en Astra Control. Por ejemplo, puede ver el estado de una operación de backup, restauración o clonado en ejecución, y ver detalles como un porcentaje completado y el tiempo restante estimado. Es posible ver el estado de una operación programada que se haya ejecutado o una operación que se inició manualmente.

Mientras ve una tarea en ejecución o completada, puede expandir los detalles de la tarea para ver el estado de cada una de las subtareas. La barra de progreso de la tarea es verde para las tareas en curso o completadas, azul para las tareas canceladas y rojo para las tareas que han fallado debido a un error.


NOTE: Para las operaciones de clonado, las subtareas consisten en una operación de restauración de Snapshot y de Snapshot.

Para obtener más información sobre las tareas que han fallado, consulte link:monitor-account-activity.html["Controlar la actividad de la cuenta"].

.Pasos
. Mientras se está ejecutando una tarea, vaya a *aplicaciones*.
. Seleccione el nombre de una aplicación de la lista.
. En los detalles de la aplicación, seleccione la ficha *tareas*.
+
Puede ver detalles de tareas actuales o pasadas y filtrar por estado de tarea.




NOTE: Las tareas se conservan en la lista *tareas* durante un máximo de 24 horas. Puede configurar este límite y otros ajustes del monitor de tareas mediante https://docs.netapp.com/us-en/astra-automation/["API de control Astra"^].
