---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore, ontap-nas-economy, disruptive, migration 
summary: Astra Control puede restaurar la configuración de sus aplicaciones y el almacenamiento persistente a partir de una copia Snapshot o una copia de seguridad. Los backups de almacenamiento persistente se transfieren desde su almacén de objetos, de modo que la restauración a partir de un backup existente se completa lo más rápido. 
---
= Restaurar aplicaciones
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control puede restaurar su aplicación a partir de una instantánea o una copia de seguridad. La restauración a partir de una snapshot existente será más rápida cuando se restaure la aplicación en el mismo clúster. Puede utilizar la interfaz de usuario de Astra Control o. https://docs.netapp.com/us-en/astra-automation/index.html["La API de control Astra"^] para restaurar aplicaciones.


NOTE: Si se agrega un filtro de espacio de nombres a un enlace de ejecución que se ejecuta después de una operación de restauración o clonado y el origen y destino de la restauración o clonado se encuentran en diferentes espacios de nombres, el filtro de espacio de nombres solo se aplica al espacio de nombres de destino.

.Antes de empezar
* *Proteja sus aplicaciones primero*: Se recomienda encarecidamente que tome una instantánea o una copia de seguridad de su aplicación antes de restaurarla. Esto le permitirá clonar desde la snapshot o backup si la restauración no se realiza correctamente.
* *Comprobar volúmenes de destino*: Si restaura a una clase de almacenamiento diferente, asegúrese de que la clase de almacenamiento utilice el mismo modo de acceso de volumen persistente (por ejemplo, ReadWriteMany). Se producirá un error en la operación de restauración si el modo de acceso al volumen persistente de destino es diferente. Por ejemplo, si el volumen persistente de origen utiliza el modo de acceso RWX, seleccionando una clase de almacenamiento de destino que no pueda proporcionar RWX, como Azure Managed Disks, AWS EBS, Google Persistent Disk o. `ontap-san`, hará que falle la operación de restauración. Para obtener más información sobre los modos de acceso a volúmenes persistentes, consulte la https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes["Kubernetes"^] documentación.
* *Planificar necesidades de espacio*: Cuando se realiza una restauración in situ de una aplicación que utiliza almacenamiento ONTAP de NetApp, el espacio utilizado por la aplicación restaurada puede duplicarse. Después de realizar una restauración sin movimiento, elimine las instantáneas no deseadas de la aplicación restaurada para liberar espacio de almacenamiento.
* *Controladores de clase de almacenamiento compatibles*: Astra Control admite la restauración de copias de seguridad mediante clases de almacenamiento respaldadas por los siguientes controladores:
+
** `ontap-nas`
** `ontap-nas-economy`
** `ontap-san`
** `ontap-san-economy`


* *(Solo controlador económico de ontap-nas) Copias de seguridad y restauraciones*: Antes de realizar copias de seguridad o restaurar una aplicación que utiliza una clase de almacenamiento respaldada por el `ontap-nas-economy` controlador, compruebe que el link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["El directorio Snapshot del sistema de administración de almacenamiento de ONTAP está oculto"]. Si no se oculta este directorio, se puede perder el acceso a la aplicación, especialmente si se utiliza NFSv3.


[CAUTION]
====
La ejecución de una operación de restauración sin movimiento en una aplicación que comparte recursos con otra aplicación puede tener resultados no intencionados. Los recursos compartidos entre las aplicaciones se reemplazan cuando se realiza una restauración sin movimiento en una de las aplicaciones.

====
.Pasos
. Seleccione *aplicaciones* y, a continuación, seleccione el nombre de una aplicación.
. En el menú Opciones de la columna Acciones, seleccione *Restaurar*.
. Elija el tipo de restauración:
+
** *Restaurar en espacios de nombres originales*: Utilice este procedimiento para restaurar la aplicación en su sitio al cluster original.
+
... Seleccione la instantánea o la copia de seguridad que desea utilizar para restaurar la aplicación en el lugar, lo que revierte la aplicación a una versión anterior de sí misma.
... Seleccione *Siguiente*.
+

NOTE: Si se restaura en un espacio de nombres que se eliminó previamente, se crea un espacio de nombres nuevo con el mismo nombre como parte del proceso de restauración. Cualquier usuario que tenga derechos para administrar aplicaciones en el espacio de nombres previamente eliminado debe restaurar manualmente los derechos en el espacio de nombres recién creado.



** *Restaurar en nuevos espacios de nombres*: Utilice este procedimiento para restaurar la aplicación en otro clúster o con diferentes espacios de nombres desde el origen. También puede usar este procedimiento para migrar una aplicación a una clase de almacenamiento diferente.
+
... Especifique el nombre de la aplicación restaurada.
... Elija el clúster de destino de la aplicación que desea restaurar.
... Introduzca un espacio de nombres de destino para cada espacio de nombres de origen asociado a la aplicación.
+

NOTE: Astra Control crea nuevos espacios de nombres de destino como parte de esta opción de restauración. Los espacios de nombres de destino que especifique no deben estar ya presentes en el clúster de destino.

... Seleccione *Siguiente*.
... Seleccione la instantánea o la copia de seguridad que desea utilizar para restaurar la aplicación.
... Seleccione *Siguiente*.
... Elija una de las siguientes opciones:
+
**** *Restaurar usando clases de almacenamiento originales*: La aplicación utiliza la clase de almacenamiento asociada originalmente a menos que no exista en el clúster de destino. En este caso, se utilizará la clase de almacenamiento predeterminada para el clúster.
**** *Restaurar usando una clase de almacenamiento diferente*: Seleccione una clase de almacenamiento que exista en el clúster de destino. Todos los volúmenes de aplicaciones, independientemente de sus tipos de almacenamiento asociados originalmente, se migrarán a esta clase de almacenamiento diferente como parte de la restauración.


... Seleccione *Siguiente*.




. Elija cualquier recurso para filtrar:
+
** *Restaurar todos los recursos*: Restaurar todos los recursos asociados con la aplicación original.
** *Filtrar recursos*: Especificar reglas para restaurar un subconjunto de los recursos originales de la aplicación:
+
... Seleccione incluir o excluir recursos de la aplicación restaurada.
... Seleccione *Agregar regla de inclusión* o *Agregar regla de exclusión* y configure la regla para filtrar los recursos correctos durante la restauración de la aplicación. Puede editar una regla o eliminarla y volver a crear una regla hasta que la configuración sea correcta.
+

NOTE: Para obtener más información sobre la configuración de reglas de inclusión y exclusión, consulte <<Filtre recursos durante una restauración de aplicación>>.





. Seleccione *Siguiente*.
. Revise los detalles sobre la acción de restauración cuidadosamente, escriba “restaurar” (si se le solicita) y seleccione *Restaurar*.




== [Vista previa técnica] Restaurar a partir del backup mediante un recurso personalizado (CR)

Es posible restaurar datos desde un backup con un archivo de recurso personalizado (CR) en otro espacio de nombres o en el espacio de nombres de origen original.

[role="tabbed-block"]
====
.Restaurar desde una copia de seguridad con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre `astra-control-backup-restore-cr.yaml`. Actualiza los valores entre paréntesis <> para que coincidan con tu entorno de Astra Control y la configuración del clúster:
+
** <CR_NAME>: El nombre de esta operación de CR; seleccione un nombre sensible para su entorno.
** <APPVAULT_NAME>: El nombre del AppVault donde se almacena el contenido del backup.
** <BACKUP_PATH>: Ruta dentro de AppVault, donde se almacena el contenido del backup. Por ejemplo:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
** <SOURCE_NAMESPACE>: El espacio de nombres de origen de la operación de restauración.
** <DESTINATION_NAMESPACE>: El espacio de nombres de destino de la operación de restauración.
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: BackupRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appVaultRef: <APPVAULT_NAME>
  appArchivePath: <BACKUP_PATH>
  namespaceMapping: [{"source": "<SOURCE_NAMESPACE>", "destination": "<DESTINATION_NAMESPACE>"}]
----




Directiva no resuelta en <stdin> - Include:../_include/selective-restore-cr.adoc[]

. Después de rellenar el `astra-control-backup-restore-cr.yaml` Con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f astra-control-backup-restore-cr.yaml
----


--
.Restaure desde un backup al espacio de nombres original con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre `astra-control-backup-ipr-cr.yaml`. Actualiza los valores entre paréntesis <> para que coincidan con tu entorno de Astra Control y la configuración del clúster:
+
** <CR_NAME>: El nombre de esta operación de CR; seleccione un nombre sensible para su entorno.
** <APPVAULT_NAME>: El nombre del AppVault donde se almacena el contenido del backup.
** <BACKUP_PATH>: Ruta dentro de AppVault, donde se almacena el contenido del backup. Por ejemplo:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: BackupInplaceRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appVaultRef: <APPVAULT_NAME>
  appArchivePath: <BACKUP_PATH>
----




Directiva no resuelta en <stdin> - Include:../_include/selective-restore-cr.adoc[]

. Después de rellenar el `astra-control-backup-ipr-cr.yaml` Con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f astra-control-backup-ipr-cr.yaml
----


--
====


== [Vista PREVIA TÉCNICA] Restauración a partir de una instantánea con un recurso personalizado (CR)

Puede restaurar datos desde una copia Snapshot con un archivo de recurso personalizado (CR) en un espacio de nombres diferente o en el espacio de nombres de origen original.

[role="tabbed-block"]
====
.Restaurar desde instantánea con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre `astra-control-snapshot-restore-cr.yaml`. Actualiza los valores entre paréntesis <> para que coincidan con tu entorno de Astra Control y la configuración del clúster:
+
** <CR_NAME>: El nombre de esta operación de CR; seleccione un nombre sensible para su entorno.
** <APPVAULT_NAME>: El nombre del AppVault donde se almacena el contenido del backup.
** <BACKUP_PATH>: Ruta dentro de AppVault, donde se almacena el contenido del backup. Por ejemplo:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
** <SOURCE_NAMESPACE>: El espacio de nombres de origen de la operación de restauración.
** <DESTINATION_NAMESPACE>: El espacio de nombres de destino de la operación de restauración.
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appArchivePath: <BACKUP_PATH>
  appVaultRef: <APPVAULT_NAME>
  namespaceMapping: [{"source": "<SOURCE_NAMESPACE>", "destination": "<DESTINATION_NAMESPACE>"}]
----




Directiva no resuelta en <stdin> - Include:../_include/selective-restore-cr.adoc[]

. Después de rellenar el `astra-control-snapshot-restore-cr.yaml` Con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f astra-control-snapshot-restore-cr.yaml
----


--
.Restauración de una snapshot al espacio de nombres original con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre `astra-control-snapshot-ipr-cr.yaml`. Actualiza los valores entre paréntesis <> para que coincidan con tu entorno de Astra Control y la configuración del clúster:
+
** <CR_NAME>: El nombre de esta operación de CR; seleccione un nombre sensible para su entorno.
** <APPVAULT_NAME>: El nombre del AppVault donde se almacena el contenido del backup.
** <BACKUP_PATH>: Ruta dentro de AppVault, donde se almacena el contenido del backup. Por ejemplo:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: SnapshotInplaceRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appArchivePath: <BACKUP_PATH>
  appVaultRef: <APPVAULT_NAME>
----




Directiva no resuelta en <stdin> - Include:../_include/selective-restore-cr.adoc[]

. Después de rellenar el `astra-control-snapshot-ipr-cr.yaml` Con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f astra-control-snapshot-ipr-cr.yaml
----


--
====
.Resultado
Astra Control restaura la aplicación en función de la información proporcionada. Si restauró la aplicación en un lugar, el contenido de los volúmenes persistentes existentes se reemplaza por el contenido de los volúmenes persistentes de la aplicación restaurada.


NOTE: Después de una operación de protección de datos (clonado, backup o restauración) y un posterior tamaño de volumen persistente, se produce un retraso de hasta veinte minutos antes de que se muestre el tamaño del nuevo volumen en la interfaz de usuario web. La operación de protección de datos se realiza correctamente en cuestión de minutos, y se puede utilizar el software de gestión para el back-end de almacenamiento para confirmar el cambio de tamaño del volumen.


NOTE: Cualquier usuario miembro con restricciones de espacio de nombres por nombre/ID de espacio de nombres o por etiquetas de espacio de nombres puede clonar o restaurar una aplicación en un nuevo espacio de nombres en el mismo clúster o en cualquier otro clúster de la cuenta de su organización. Sin embargo, el mismo usuario no puede acceder a la aplicación clonada o restaurada en el nuevo espacio de nombres. Después de que una operación de clonado o restauración crea un nuevo espacio de nombres, el administrador/propietario de la cuenta puede editar la cuenta de usuario miembro y actualizar las restricciones de roles para el usuario afectado a fin de otorgar acceso al nuevo espacio de nombres.



== Filtre recursos durante una restauración de aplicación

Puede agregar una regla de filtro a un link:../use/restore-apps.html["restaurar"] operación que especificará los recursos de aplicación existentes que se incluirán o excluirán de la aplicación restaurada. Puede incluir o excluir recursos basados en un espacio de nombres, etiqueta o GVK (GroupVersionKind) especificado.

.Lea más sobre Incluir y excluir escenarios
[%collapsible]
====
* *Selecciona una regla de inclusión con espacios de nombres originales (restauración in situ)*: Los recursos de aplicación existentes que definas en la regla se eliminarán y reemplazarán por aquellos de la instantánea o copia de seguridad seleccionada que estés utilizando para la restauración. Cualquier recurso que no especifique en la regla Incluir permanecerá sin cambios.
* *Selecciona una regla de inclusión con nuevos espacios de nombres*: Usa la regla para seleccionar los recursos específicos que deseas en la aplicación restaurada. Los recursos que no especifique en la regla Incluir no se incluirán en la aplicación restaurada.
* *Selecciona una regla de exclusión con espacios de nombres originales (restauración in situ)*: Los recursos que especifiques para ser excluidos no se restaurarán y permanecerán sin cambios. Los recursos que no especifique para excluir se restaurarán de la Snapshot o el backup. Todos los datos de los volúmenes persistentes se eliminarán y volverán a crear si el StatefulSet correspondiente forma parte de los recursos filtrados.
* *Selecciona una regla de exclusión con nuevos espacios de nombres*: Usa la regla para seleccionar los recursos específicos que deseas eliminar de la aplicación restaurada. Los recursos que no especifique para excluir se restaurarán de la Snapshot o el backup.


====
Las reglas son tipos de inclusión o exclusión. Las reglas que combinan la inclusión y exclusión de recursos no están disponibles.

.Pasos
. Una vez que haya elegido filtrar recursos y seleccionado una opción Incluir o Excluir en el asistente Restaurar aplicación, seleccione *Agregar regla de inclusión* o *Agregar regla de exclusión*.
+

NOTE: No puede excluir ningún recurso en el ámbito del clúster que Astra Control incluya automáticamente.

. Configure la regla de filtro:
+

NOTE: Debe especificar al menos un espacio de nombres, una etiqueta o un GVK. Asegúrese de que los recursos que retenga después de aplicar las reglas de filtro sean suficientes para mantener la aplicación restaurada en buen estado.

+
.. Seleccione un espacio de nombres específico para la regla. Si no hace una selección, se usarán todos los espacios de nombres en el filtro.
+

NOTE: Si la aplicación contenía originalmente varios espacios de nombres y la restauraba en nuevos espacios de nombres, todos los espacios de nombres se crearán incluso si no contienen recursos.

.. (Opcional) Introduzca un nombre de recurso.
.. (Opcional) *Selector de etiquetas*: Incluye a. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["selector de etiquetas"^] para agregar a la regla. El selector de etiquetas se utiliza para filtrar sólo los recursos que coincidan con la etiqueta seleccionada.
.. (Opcional) Seleccione *Usar GVK (GroupVersionKind) configurado para filtrar recursos* para opciones de filtrado adicionales.
+

NOTE: Si utiliza un filtro GVK, debe especificar Versión y Tipo.

+
... (Opcional) *Grupo*: En la lista desplegable, seleccione el grupo API de Kubernetes.
... *Kind*: En la lista desplegable, seleccione el esquema de objeto para el tipo de recurso de Kubernetes a utilizar en el filtro.
... *Versión*: Seleccione la versión de la API de Kubernetes.




. Revise la regla que se crea en función de las entradas.
. Seleccione *Agregar*.
+

TIP: Puede crear tantas reglas de inclusión y exclusión de recursos como desee. Las reglas aparecen en el resumen de la aplicación de restauración antes de iniciar la operación.


