---
sidebar: sidebar 
permalink: get-started/add-private-self-managed-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: Una vez configurado su entorno, estará listo para crear un clúster de Kubernetes y, a continuación, añadirlo al servicio Astra Control. 
---
= Añade un clúster privado autogestionado a Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Una vez configurado su entorno, estará listo para crear un clúster de Kubernetes y, a continuación, añadirlo al servicio Astra Control.

Un clúster autogestionado es un clúster que usted aprovisiona y gestiona directamente. Astra Control Service admite clústeres autogestionados que se ejecutan en un entorno de cloud público. Puede agregar un clúster autogestionado a Astra Control Service cargando un `kubeconfig.yaml` archivo. Deberá asegurarse de que el clúster cumple los requisitos que se indican aquí.



== Distribuciones de Kubernetes compatibles

Puede utilizar Astra Control Service para gestionar los siguientes tipos de clústeres privados autogestionados:

|===
| Distribución de Kubernetes | Versiones compatibles 


| Azure Kubernetes Service en HCI de pila de Azure | Azure Stack HCI 21H2 y 22H2 con AKS 1,23 y 1,24 


| Anthos de Google | 1,12 hasta 1,14 


| Kubernetes (ascendente) | 1,24 a 1,26 (se requiere Astra Trident 22,10 o posterior para Kubernetes 1,25 o posterior) 


| Motor Kubernetes de rancher (RKE) | RKE 1,3 con Rancher 2,6
RKE 1,4 con Rancher 2,7
RKE 2 (v1,23.x) con Rancher 2,6
RKE 2 (v1,24.x) con Rancher 2,7 


| OpenShift Container Platform de Red Hat | 4,10 hasta 4,12 


| Grid de Kubernetes de VMware Tanzania | 1,6 


| VMware Tanzu Kubernetes Grid Integrated Edition | 1,14 y 1,15 
|===
En estas instrucciones se asume que ya ha creado un clúster privado y ha preparado un método seguro para acceder de forma remota a él.

Tienes que realizar las siguientes tareas para añadir tu clúster privado a Astra Control Service:

* <<Instale el operador del conector Astra>>
* <<Configure el almacenamiento persistente>>
* <<Añada el clúster autogestionado privado a Astra Control Service>>




== Instale el operador del conector Astra

Debe instalar el operador Astra Connector en el clúster privado. Si utiliza un host de Bastion, emita estos comandos desde la línea de comandos del host de Bastion.

.Pasos
. Clonar el operador de Astra Connector, el repositorio de GitHub:
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. Cambie los directorios al nivel superior del paquete de operadores sin empaquetar para que pueda ver el `astraconnector_operator.yaml` archivo con `ls` comando.
. Cree un espacio de nombres para el operador Astra Connector.
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. Aplique el `astraconnector_operator.yaml` archivo en el espacio de nombres del operador.
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. Cree un espacio de nombres para los componentes del clúster privado.
+
[source, console]
----
kubectl create ns astra-connector
----
. Genere un token de API de control Astra utilizando las instrucciones del https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Documentación de Astra Automation"^].
. Modifique el archivo de configuración de ejemplo en el directorio config/samples del repositorio de operadores de Astra Connector a fin de incluir valores específicos de su entorno para las siguientes claves:
+
** `spec.natssync-client.cloud-bridge-url`
** `spec.astra.token`
** `spec.astra.clusterName`
+

NOTE: `spec.astra.clusterName` Solo es necesario si va a importar un clúster AKS privado y no proporciona el archivo kubeconfig a Astra Control Service. Elimine esta línea si este no es el caso.

** `spec.astra.accountId`
+
Por ejemplo:

+
[listing]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-private-AKS-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----


. Aplique la definición de recurso personalizado de Astra Connector (CRD).
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. Compruebe el estado del conector Astra.
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
Debería ver una salida similar a la siguiente:

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== Configure el almacenamiento persistente

Configure el almacenamiento persistente para el clúster. Consulte la documentación para empezar para obtener más información sobre la configuración del almacenamiento persistente:

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Configure Microsoft Azure con Azure NetApp Files"^]
* link:set-up-microsoft-azure-with-amd.html["Configure Microsoft Azure con discos gestionados de Azure"^]


endif::azure[]

ifdef::aws[]

* link:set-up-amazon-web-services.html["Configure Amazon Web Services"^]


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Configure Google Cloud"^]


endif::gcp[]



== Añada el clúster autogestionado privado a Astra Control Service

Ahora puede añadir el clúster privado a Astra Control Service.

.Antes de empezar
[%collapsible%open]
====
Un clúster autogestionado es un clúster que usted aprovisiona y gestiona directamente. Astra Control Service admite clústeres autogestionados que se ejecutan en un entorno de cloud público. Sus clústeres autogestionados pueden usar Astra Trident para interactuar con los servicios de almacenamiento de NetApp, o pueden utilizar controladores de interfaz de almacenamiento de contenedores (CSI) para interactuar con Amazon Elastic Block Store (EBS), Azure Managed Disks y Google Persistent Disk.

Astra Control Service es compatible con clústeres autogestionados que utilizan las siguientes distribuciones de Kubernetes:

* OpenShift Container Platform de Red Hat
* Motor Kubernetes del rancher
* Subida de Kubernetes


Su clúster autogestionado debe cumplir con los siguientes requisitos:

* El clúster debe estar accesible a través de Internet.
* No se puede alojar el clúster en su red local; debe alojarse en un entorno de cloud público.
* Si está utilizando o planea utilizar almacenamiento habilitado con controladores CSI, se deben instalar los controladores CSI adecuados en el clúster. Para obtener más información sobre el uso de los controladores CSI para integrar el almacenamiento, consulte la documentación del servicio de almacenamiento.
* Tiene acceso al archivo kubeconfig de cluster que incluye solo un elemento de contexto. Siga link:create-kubeconfig.html["estas instrucciones"^] para generar un archivo kubeconfig.
* *Sólo rancher*: Al administrar clústeres de aplicaciones en un entorno Rancher, modifique el contexto predeterminado del clúster de aplicaciones en el archivo kubeconfig proporcionado por Rancher para utilizar un contexto de plano de control en lugar del contexto del servidor API Rancher. Esto reduce la carga en el servidor API de Rancher y mejora el rendimiento.
* *Astra Trident*: Si estás usando o planeas usar el almacenamiento de NetApp, asegúrate de haber instalado la última versión de Astra Trident. Si Astra Trident ya está instalado, link:check-astra-trident-version.html["compruebe que es la versión más reciente"^].
+

NOTE: Puede hacerlo https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#choose-the-deployment-method["Ponga en marcha Astra Trident"^] Mediante el operador de Trident (manualmente o mediante el gráfico Helm) o. `tridentctl`. Antes de instalar o actualizar Astra Trident, revise https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["compatibles con front-ends, back-ends y configuraciones de host"^].

+
** *El backend de almacenamiento Astra Trident configurado*: Debe haber al menos un backend de almacenamiento Astra Trident https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-postdeployment.html#step-1-create-a-backend["configurado"^] en el clúster.
** *Clases de almacenamiento Astra Trident configuradas*: Al menos una clase de almacenamiento Astra Trident debe ser https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["configurado"^] en el clúster. Si se configura una clase de almacenamiento predeterminada, asegúrese de que sólo una clase de almacenamiento tenga esa anotación.
** *Astra Trident volume snapshot Controller y volume snapshot class instalado y configurado*: La controladora de instantáneas de volumen debe ser https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller["instalado"^] Para poder crear instantáneas en Astra Control. Al menos un Astra Trident `VolumeSnapshotClass` ha sido https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#step-1-set-up-a-volumesnapshotclass["configuración"^] por un administrador.




====
.Pasos
. En el Panel de control, seleccione *gestionar clúster Kubernetes*.
+
Siga las instrucciones para añadir el clúster.

. *Proveedor*: Selecciona la pestaña *Otro* para agregar detalles sobre tu cluster autogestionado.
. *Otros*: Proporcione detalles sobre su cluster autogestionado cargando un `kubeconfig.yaml` o bien, pegue el contenido de `kubeconfig.yaml` desde el portapapeles.
+

NOTE: Si crea el suyo propio `kubeconfig` file, debe definir sólo un elemento de contexto *uno* en él. Consulte https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Documentación de Kubernetes"^] para obtener información acerca de cómo crear `kubeconfig` archivos.

. *Nombre de credencial*: Proporciona un nombre para la credencial de clúster autogestionada que estás cargando en Astra Control. De forma predeterminada, el nombre de las credenciales se completa automáticamente como nombre del clúster.
. *Identificador de ruta privado*: Introduce el identificador de ruta privado, que puedes obtener del Astra Connector. Si consulta el Astra Connector a través del `kubectl get` comando, el identificador de ruta privada se denomina `ASTRACONNECTORID`.
+

NOTE: El identificador de ruta privada es el nombre asociado con Astra Connector que permite gestionar un clúster de Kubernetes privado con Astra. En este contexto, un clúster privado es un clúster de Kubernetes que no expone su servidor API a Internet.

. Seleccione *Siguiente*.
. (Opcional) *Almacenamiento*: Opcionalmente, seleccione la clase de almacenamiento que desea que las aplicaciones de Kubernetes implementadas en este clúster utilicen de forma predeterminada.
+
.. Para seleccionar una nueva clase de almacenamiento predeterminada para el clúster, active la casilla de verificación *Asignar una nueva clase de almacenamiento predeterminada*.
.. Seleccione una nueva clase de almacenamiento predeterminada de la lista.
+
[NOTE]
====
Cada servicio de almacenamiento de proveedor de cloud muestra la siguiente información sobre el precio, el rendimiento y la resiliencia:

ifdef::gcp[]

*** Cloud Volumes Service para Google Cloud: Información de precio, rendimiento y resiliencia
*** Google Persistent Disk: No hay información de precio, rendimiento ni resiliencia disponible


endif::gcp[]

ifdef::azure[]

*** Azure NetApp Files: Información sobre rendimiento y resiliencia
*** Discos administrados de Azure: No hay información de precios, rendimiento ni resiliencia disponible


endif::azure[]

ifdef::aws[]

*** Amazon Elastic Block Store: No dispone de información de precio, rendimiento o resiliencia
*** Amazon FSX para ONTAP de NetApp: Sin información de precio, rendimiento ni resiliencia disponible


endif::aws[]

*** Cloud Volumes ONTAP de NetApp: No hay información de precio, rendimiento ni resiliencia disponible


====
+
Cada clase de almacenamiento puede utilizar uno de los siguientes servicios:





ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service para Google Cloud"^]
* https://cloud.google.com/persistent-disk/["Disco persistente de Google"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Discos gestionados de Azure"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX para ONTAP de NetApp"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["Cloud Volumes ONTAP de NetApp"^]
+
Más información acerca de link:../learn/aws-storage.html["Clases de almacenamiento para clústeres de Amazon Web Services"]. Más información acerca de link:../learn/azure-storage.html["Clases de almacenamiento para clústeres de AKS"]. Más información acerca de link:../learn/choose-class-and-size.html["Clases de almacenamiento para clústeres GKE"].

+
.. Seleccione *Siguiente*.
.. *Revisar y aprobar*: Revise los detalles de la configuración.
.. Selecciona *Add* para agregar el clúster a Astra Control Service.






== Cambie la clase de almacenamiento predeterminada

Es posible cambiar la clase de almacenamiento predeterminada para un clúster de.



=== Cambie la clase de almacenamiento predeterminada con Astra Control

Puede cambiar la clase de almacenamiento predeterminada para un clúster de Astra Control. Si su clúster utiliza un servicio de fondo de almacenamiento previamente instalado, es posible que no pueda utilizar este método para cambiar la clase de almacenamiento predeterminada (la acción *establecer como predeterminada* no se puede seleccionar). En este caso, usted puede <<Cambie la clase de almacenamiento predeterminada con la línea de comandos>>.

.Pasos
. En la interfaz de usuario de Astra Control Service, seleccione *Clusters*.
. En la página *Clusters*, seleccione el clúster que desea cambiar.
. Seleccione la ficha *almacenamiento*.
. Seleccione la categoría *clases de almacenamiento*.
. Seleccione el menú *acciones* para la clase de almacenamiento que desea establecer como predeterminada.
. Seleccione *establecer como predeterminado*.




=== Cambie la clase de almacenamiento predeterminada con la línea de comandos

Es posible cambiar la clase de almacenamiento predeterminada para un clúster mediante comandos de Kubernetes. Este método funciona independientemente de la configuración del clúster.

.Pasos
. Inicie sesión en su clúster de Kubernetes.
. Enumere las clases de almacenamiento del clúster:
+
[source, console]
----
kubectl get storageclass
----
. Quite la designación predeterminada de la clase de almacenamiento predeterminada. Sustituya <SC_NAME> por el nombre de la clase de almacenamiento:
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. Seleccione una clase de almacenamiento diferente de forma predeterminada. Sustituya <SC_NAME> por el nombre de la clase de almacenamiento:
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. Confirme la nueva clase de almacenamiento predeterminada:
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]
