---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: Una vez configurado su entorno, estará listo para crear un clúster de Kubernetes y, a continuación, añadirlo al servicio Astra Control. 
---
= Gestione clústeres privados desde Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Puede utilizar Astra Control Service para gestionar clústeres privados de AKS. En estas instrucciones se presupone que ya ha creado un clúster de AKS privado y que ha preparado un método seguro para acceder a él de forma remota; para obtener más información sobre cómo crear clústeres de AKS privados y cómo acceder a ellos, consulte la https://docs.microsoft.com/azure/aks/private-clusters["Documentación de Azure"^].

* <<Instale el operador del conector Astra>>
* <<Configure el almacenamiento persistente>>
* <<Agregue el clúster privado a Astra Control Service>>




== Instale el operador del conector Astra

Debe instalar el operador Astra Connector en un clúster AKS privado. Si utiliza un host de Bastion, emita estos comandos desde la línea de comandos del host de Bastion.

.Pasos
. Clonar el operador de Astra Connector, el repositorio de GitHub:
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. Cambie los directorios al nivel superior del paquete de operadores sin empaquetar para que pueda ver el `astraconnector_operator.yaml` archivo con `ls` comando.
. Cree un espacio de nombres para el operador Astra Connector.
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. Aplique el `astraconnector_operator.yaml` archivo en el espacio de nombres del operador.
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. Cree un espacio de nombres para los componentes del clúster privado.
+
[source, console]
----
kubectl create ns astra-connector
----
. Genere un token de API de control Astra utilizando las instrucciones del https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Documentación de Astra Automation"^].
. Modifique el archivo de configuración de ejemplo del directorio config/Samples del repositorio del operador Astra Connector para que se ajuste a sus necesidades.
. Aplique la definición de recurso personalizado de Astra Connector (CRD).
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. Compruebe el estado del conector Astra.
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
Debe hacer referencia a una salida similar a la siguiente:

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== Configure el almacenamiento persistente

Configure el almacenamiento persistente para el clúster. Puede usar discos gestionados de Azure NetApp Files o Azure. Consulte la documentación de Get Started para obtener más información sobre la configuración de Azure con estas opciones:

* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-anf.html["Configure Microsoft Azure con Azure NetApp Files"]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html["Configure Microsoft Azure con discos gestionados de Azure"]




== Agregue el clúster privado a Astra Control Service

Ahora puede agregar el clúster de AKS privado al servicio de control Astra. Siga el flujo de trabajo estándar para agregar un clúster a Astra Control Service: https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html["Empiece a gestionar los clústeres de Kubernetes desde Astra Control Service"].
